apiVersion: apps/v1
kind: Deployment
metadata:
  name: agones-server-analytics
spec:
  selector:
    matchLabels:
      app: agones-server-analytics
  replicas: 2
  template:
    metadata:
      labels:
        app: agones-server-analytics
    spec:
      containers:
      - name: agones-server
        image: agones/server:latest
        ports:
        - containerPort: 27960
        - containerPort: 27960
      - name: analytics
        image: analytics_container_placeholder:latest
        ports:
        - containerPort: 8080
