apiVersion: v1
kind: Service
metadata:
  name: my-sidecar-service
spec:
  selector:
    app: my-sidecar-app
  ports:
  - name: json-router
    port: 8080
    protocol: UDP
    targetPort: 8080
  - name: data-processor
    port: 8080
    protocol: UDP
    targetPort: 8080
